### ISSUE TITLE
onClick.Add

### ISSUE THREAD

**Issue by easyboy3** [passiony/ETFramework#1]
![image](https://user-images.githubusercontent.com/14209787/90984002-cc1be980-e5a4-11ea-95b7-c4aa5110ce76.png)
.onClick.Add(this.EnterMap);
Add方法提示是扩展方法，但是我怎么都跟踪不进去，假如我也想加扩展方法，在哪里加呢？

**Comment by passiony** [comment]
namespace ETModel
{
    public static class ButtonHelper
    {
        public static void Add(this Button.ButtonClickedEvent buttonClickedEvent, Action action)
        {
            buttonClickedEvent.AddListener(() => { action(); });
        }
    }
}
